### ISSUE TITLE
[DOCS] Create Milestones for the project

### ISSUE THREAD

**Issue by CankutER** [SWE574-G3/SWE-574-G3#13]
### Description:
Provide a description of documentation

- **Type of Documentation:**
  - [ ] Wiki page
  - [ ] Design document
  - [X] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [X] It doesn't exist
  
### Resources
Add Resource if applicable

**Comment by CankutER** [comment]
Milestones have been created.
https://github.com/SWE574-G3/SWE-574-G3/milestones
