### ISSUE TITLE
[DOCS] Wiki: Requirements Page

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#6]
### Description:
Filling contents of [Requirements](https://github.com/Oguzoz1/SWE-574-G3/wiki/Requirements) page on wiki which should contain elicitation questions, functional, non-functional requirements and a glossary. Some requirements should be discussed and if it is needed, refined. 

### Tasks:
  - [x] Elicitation
  - [x] Functional
  - [ ] Non-functional
  - [x] Glossary

- **Type of Documentation:**
  - [x] Wiki page
  - [ ] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [x] It exists need update
  - [ ] It doesn't exist
  
### Resources
[EARS format for requirement statement](https://alistairmavin.com/ears/)
[Oguz's Requirement Page](https://github.com/Oguzoz1/Studyhole-Community-Management/wiki/Functional-Requirements)

**Comment by Oguzoz1** [comment]
Functional Requirements for existing project and needs has been set. Some of the elicitations are transferred and shall be updated.

**Comment by Oguzoz1** [comment]
[Glossary](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#glossary) is added.

**Comment by niloaydin** [comment]
[Commit Message](https://github.com/SWE574-G3/SWE-574-G3/wiki/Coding-Standards) standards is added.

**Comment by AhmetZ06** [comment]
[Activity Feed Requirements ](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#activity-feed-requirements) are added

**Comment by AhmetZ06** [comment]
[Table of Contents](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#table-of-contents) is added.
